### ISSUE TITLE
could provide better error messages for programmer errors

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-extsprintf#13]
The error messages produced by extsprintf could contain a lot more information, like the format string and which format character generated the error.  This would help people more quickly identify the problem, particularly when extsprintf is several layers of abstraction down (e.g., in the case of node-verror).  See node-verror#30 for an example.

**Comment by davepacheco** [comment]
All of the messages now include the complete format string, the conversion specifier with the problem, what character that conversion specifier was at, and of course a description of the problem.  As an example, this test program:

```javascript
var sprintf = require('./lib/extsprintf').sprintf;
sprintf('%s');
```

used to produce:

```
$ node busted.js 

/Users/dap/work/reference/joyent/node-extsprintf/lib/extsprintf.js:72
			throw (new Error('too few args to sprintf'));
			       ^
Error: too few args to sprintf
    at jsSprintf (/Users/dap/work/reference/joyent/node-extsprintf/lib/extsprintf.js:72:11)
    at Object.<anonymous> (/Users/dap/work/reference/joyent/node-extsprintf/busted.js:2:1)
...
```

and now it produces:

```
$ node busted.js 

/Users/dap/work/node-extsprintf/lib/extsprintf.js:97
			throw (jsError(ofmt, convposn, curconv,
			       ^
Error: format string "%s": conversion specifier "%s" at character 1 has no matching argument (too few arguments passed)
    at jsError (/Users/dap/work/node-extsprintf/lib/extsprintf.js:173:10)
    at jsSprintf (/Users/dap/work/node-extsprintf/lib/extsprintf.js:97:11)
    at Object.<anonymous> (/Users/dap/work/node-extsprintf/busted.js:2:1)
...
```

Here are some other examples from the new test case for this:

```
test case: missing all arguments
    args:   []
    error:  first argument must be a format string
test case: missing argument for format specifier (first char and specifier)
    args:   ["%s"]
    error:  format string "%s": conversion specifier "%s" at character 1 has no matching argument (too few arguments passed)
test case: missing argument for format specifier (later in string)
    args:   ["hello %s world %13d","big"]
    error:  format string "hello %s world %13d": conversion specifier "%13d" at character 16 has no matching argument (too few arguments passed)
test case: printing null as string
    args:   ["%d cookies %3s",15,null]
    error:  format string "%d cookies %3s": conversion specifier "%3s" at character 12 attempted to print undefined or null as a string (argument 3 to sprintf)
test case: printing undefined as string
    args:   ["%d cookies %3s ah %d",15,null,7]
    error:  format string "%d cookies %3s ah %d": conversion specifier "%3s" at character 12 attempted to print undefined or null as a string (argument 3 to sprintf)
test case: unsupported format character
    args:   ["do not use %X",13]
    error:  format string "do not use %X": conversion specifier "%X" at character 12 is not supported
test case: unsupported flags
    args:   ["%#x",13]
    error:  format string "%#x": conversion specifier "%#x" at character 1 uses unsupported flags
```

**Comment by davepacheco** [comment]
In the context of node-verror, where this came up:

```javascript
new VError('foo %s bar');
```

now produces:

```
/Users/dap/work/node-verror/node_modules/extsprintf/lib/extsprintf.js:97
			throw (jsError(ofmt, convposn, curconv,
			       ^
Error: format string "foo %s bar": conversion specifier "%s" at character 5 has no matching argument (too few arguments passed)
```

**Comment by davepacheco** [comment]
Patchset 2 is `make prepush` clean.

**Comment by davepacheco** [comment]
Review was here: https://cr.joyent.us/#/c/3012/
